//start popular Movies
export const POPULAR_MOVIES_REQUEST = 'POPULAR_MOVIES_REQUEST ';
export const POPULAR_MOVIES_FAIL = 'POPULAR_MOVIES_FAIL';
export const POPULAR_MOVIES_SUCCESS = 'POPULAR_MOVIES_SUCCESS';
//end popular Movies

export const IMAGE_SLIDER_REQUEST = 'IMAGE_SLIDER_REQUEST ';
export const IMAGE_SLIDER_FAIL = 'IMAGE_SLIDER_FAIL';
export const IMAGE_SLIDER_SUCCESS = 'IMAGE_SLIDER_SUCCESS';

export const GET_TRENDING_REQUEST = 'GET_TRENDING_REQUEST';
export const GET_TRENDING_SUCCESS = 'GET_TRENDING_SUCCESS';
export const GET_TRENDING_FAIL = 'GET_TRENDING_FAIL';

export const GET_DISCOVER_REQUEST = 'GET_DISCOVER_REQUEST';
export const GET_DISCOVER_SUCCESS = 'GET_DISCOVER_SUCCESS';
export const GET_DISCOVER_FAIL = 'GET_DISCOVER_FAIL';

export const GET_DETAILS_REQUEST = 'GET_DETAILS_REQUEST';
export const GET_DETAILS_SUCCESS = 'GET_DETAILS_SUCCESS';
export const GET_DETAILS_FAIL = 'GET_DETAILS_FAIL';
