import {combineReducers} from 'redux';
import {
  POPULAR_MOVIES_REDUCER,
  GET_SLIDER_IMAGE_REDUCER,
  GET_TRENDING_REDUCER,
  GET_DISCOVER_REDUCER,
  GET_DETAILS_REDUCER,
} from './GetDataReducer';

export const compainReducers = combineReducers({
  POPULAR_MOVIES: POPULAR_MOVIES_REDUCER,
  GET_SLIDER_IMAGE: GET_SLIDER_IMAGE_REDUCER,
  GET_TRENDING: GET_TRENDING_REDUCER,
  GET_DISCOVER: GET_DISCOVER_REDUCER,
  GET_DETAILS: GET_DETAILS_REDUCER,
});
